apiVersion: batch/v1
kind: Job
metadata: 
  name: hello-jobs
spec:
  completions: 10
  parallelism: 2
  template:
    spec:
      containers:
      - name: ubuntu 
        image: ubuntu
        command:
         - "/bin/bash"
         - "-c"
         - "/bin/echo Hello from Pod $(hostname) at $(date)"
      restartPolicy: Never     
