apiVersion: v1
kind: Pod
metadata:
  name: hello-world-on-failure-pod
spec:
  containers:
  - name: hello-world
    image: gcr.io/google-samples/hello-app:1.0
  restartPolicy: OnFailure 
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-never-pod
spec:
  containers:
  - name: hello-world
    image: gcr.io/google-samples/hello-app:1.0
  restartPolicy: Never 
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-always
spec:
  containers:
  - name: hello-world
    image: gcr.io/google-samples/hello-app:1.0
