apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  managedFields:
  - apiVersion: v1
    manager: kubectl
    operation: Update
    time: "2020-04-22T10:29:52Z"
  name: nginx-deployment
  selfLink: /api/v1/namespaces/default/services/nginx-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
