apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-sec-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  hello-world-sec-env
  template:
    metadata:
      labels:
        app: hello-world-sec-env
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        name: hello-world
        env:
        - name: app1user
          valueFrom:
            secretKeyRef:
              name: app1
              key: USERNAME
        - name: app1pass
          valueFrom:
            secretKeyRef:
              name: app1
              key: PASSWORD
        ports:
        - containerPort: 8080
